[package]
name = "app_rust"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.12.1"
chrono = "0.4.43"
dotenv = "0.15.0"
env_logger = "0.11.8"
gethostname = "1.1.0"
log = "0.4.29"
os_info = "3.14.0"
serde = { version = "1.0.228", features = ["derive"]}
version_check = "0.9.5"
