name: lab03

on: push

jobs:
  Check-code-and-docker-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.14'

      - name: Install dependencies
        run: cd app_python/; pip install -r requirements.txt

      - name: Lint
        run: flake8 app_python/app.py app_python/tests/

      - name: Test
        run: pytest app_python/tests/

      - name: Generate version
        id: gen-ver
        run: echo "VERSION=$(date +%Y.%m.%d)" >> $GITHUB_OUTPUT

      - uses: docker/setup-buildx-action@v3
      - name: Docker build and push
        uses: docker/build-push-action@v6
        with:
          context: ./app_python
          tags: kosmogor/devops:latest,kosmogor/devops:${{ steps.gen-ver.outputs.VERSION }}