name: lab03

on: push

jobs:
  Check-code-and-docker-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.14'
      - name: Install dependencies
        run: cd app_python/; pip install -r requirements.txt
      - name: Lint
        run: flake8 app_python/app.py app_python/tests/
      - name: Test
        run: pytest app_python/tests/