name: rust-lab03

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - master
    paths:
      - app_rust/
      - '!app_rust/docs/**'
      - '!app_rust/README.md'

jobs:
  Check-rust-code-and-docker-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            app_rust/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: cargo build --manifest-path app_rust/Cargo.toml --verbose

      - name: Lint
        run: cargo clippy --manifest-path app_rust/Cargo.toml

      - name: Test
        run: cargo test --manifest-path app_rust/Cargo.toml --verbose

      - name: Generate version
        id: gen-ver
        run: echo "VERSION=$(date +%Y.%m.%d)" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/setup-buildx-action@v3
      - name: Docker build and push
        uses: docker/build-push-action@v6
        with:
          context: ./app_rust
          push: true
          tags: kosmogor/devops_rust:latest,kosmogor/devops_rust:${{ steps.gen-ver.outputs.VERSION }}